# Generated by Django 4.0.2 on 2022-03-14 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Biblio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('matiere', models.CharField(max_length=200)),
                ('filiere', models.CharField(max_length=200)),
                ('nomProfesseur', models.CharField(max_length=100)),
                ('contenu', models.FileField(upload_to='sujets/%Y/%m/%d')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('matiere', models.CharField(max_length=200)),
                ('filiere', models.CharField(max_length=200)),
                ('contenu', models.FileField(upload_to='corrections/%Y/%m/%d')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('idEpreuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuve', to='Biblio.epreuve')),
            ],
        ),
    ]
